[package]
name = "libsrs"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[test]]
name = "r5rs_numerical"
path = "tests/r5rs/numerical_tests.rs"

[[test]]
name = "r5rs_procedure"
path = "tests/r5rs/procedure_tests.rs"

[[test]]
name = "r5rs_pair"
path = "tests/r5rs/pair_tests.rs"
